export const NotificationType = {
    // Social
    POST_LIKE: "POST_LIKE",
    POST_DOWNVOTE: "POST_DOWNVOTE",
    POST_COMMENT: "POST_COMMENT",
    COMMENT_REPLY: "COMMENT_REPLY",
    POST_MENTION: "POST_MENTION",
    COMMENT_MENTION: "COMMENT_MENTION",
    NEW_FOLLOWER: "NEW_FOLLOWER",
    COMMENT_UPVOTE: "COMMENT_UPVOTE",
    COMMENT_DOWNVOTE: "COMMENT_DOWNVOTE",
  
    // Appointments
    APPOINTMENT_BOOKED: "APPOINTMENT_BOOKED",
    APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",
    APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
    APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
    APPOINTMENT_REMINDER_24HR: "APPOINTMENT_REMINDER_24HR",
    APPOINTMENT_REMINDER_1HR: "APPOINTMENT_REMINDER_1HR",
    APPOINTMENT_NO_SHOW: "APPOINTMENT_NO_SHOW",
    APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
    APPOINTMENT_FAILED: "APPOINTMENT_FAILED",
  
    // Payments
    PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  
    // System
    SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT",
    ACCOUNT_VERIFICATION: "ACCOUNT_VERIFICATION",
    PASSWORD_RESET: "PASSWORD_RESET",
  };
  
  export const Priority = {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
    CRITICAL: "CRITICAL",
  };
  